apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ecosystem-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /ladder
            backend:
              serviceName: ladder-service
              servicePort: 8080
